### ISSUE TITLE
Insufficient input validation reading `StructItems`

### ISSUE THREAD

**Issue by 197g** [ababo/dtb#6]
These lines read offsets from the input binary and trust them to only specify offsets in-bounds. This leads to `panic!` while reading from the `StructItems` iterator.

https://github.com/ababo/dtb/blob/e0ce89fdf6c7c46117d2b92dacc0daec076cfa27/src/reader.rs#L89-L95

Reproduction case is attached (`cargo run --example dump`), I'll likely provide a fix PR this week.
[issue-6.zip](https://github.com/ababo/dtb/files/3588103/issue-6.zip)

**Comment by 197g** [comment]
This issue was found via [fuzzing](https://github.com/rust-fuzz/cargo-fuzz). I can also provide a PR for fuzzer integration if you want.

**Comment by ababo** [comment]
Yes, please. Will look at this tomorrow.

**Comment by ababo** [comment]
Fixed in 3a6596006e474f2d8d6ba8ec9ee2ca7ec4498dcf.
